Algoritmo "exercicio_crescente"

Var

         x, y : real

Inicio


   escreval("Digite dois numeros: ")
   leia(x)
   leia(y)
   
   enquanto x <> y faca

   se x > y entao
     escreval ("DECRESCENTE!")
     
     senao
     
     se x < y entao
        escreval ("CRESCENTE!")
        senao

        
    fimse
     fimse
   
        escreval ("Digite outros dois numeros:")
        leia (x)
        leia (y)
   

     fimenquanto




Fimalgoritmo