Algoritmo "exercicio_senha"

Var

     senha , senhaCorreta : inteiro

Inicio

       senhaCorreta <- 2002
       
      escreva ("Digite a senha:")
       leia(senha)
       
       se senha = senhaCorreta entao
          escreval ("Acesso Permitido")
          
          senao

             enquanto senha <> senhaCorreta faca
                escreva("Senha Invalida! Tente novamente:")
                
                leia(senha)

          fimenquanto
             escreval ("Acesso Permitido")
          fimse






Fimalgoritmo
